name: Generate enroute tiles

on:
  schedule:
  - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  check_edition:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
          sparse-checkout: .
      - uses: actions/checkout@v3
        with:
          ref: scripts
          path: scripts
      - name: Check if new edition is available
        run: GIT_LOG=$(git log) node ./scripts/check_enroute_edition.mjs
  # us_low:
  #   runs-on: ubuntu-latest
  #   needs: check_edition
  #   if: ${{ needs.check_edition.result == 'success' }}
  #   steps:
  #     - uses: actions/checkout@v3
  #       with:
  #         ref: scripts
  #     - name: Download US low enroute and generate tiles
  #       run: ./enroute_download
  #       env:
  #         GEONAME: US
  #         SERIES_TYPE: low
  #     - name: Upload US low enroute artifact
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: enroute
  #         path: US_low_enroute.zip
  # us_high:
  #   runs-on: ubuntu-latest
  #   needs: check_edition
  #   if: ${{ needs.check_edition.result == 'success' }}
  #   steps:
  #     - uses: actions/checkout@v3
  #       with:
  #         ref: scripts
  #     - name: Download US high enroute and generate tiles
  #       run: ./enroute_download
  #       env:
  #         GEONAME: US
  #         SERIES_TYPE: high
  #     - name: Upload US high enroute artifact
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: enroute
  #         path: US_high_enroute.zip
  # us_area:
  #   runs-on: ubuntu-latest
  #   needs: check_edition
  #   if: ${{ needs.check_edition.result == 'success' }}
  #   steps:
  #     - uses: actions/checkout@v3
  #       with:
  #         ref: scripts
  #     - name: Download US area enroute and generate tiles
  #       run: ./enroute_download
  #       env:
  #         GEONAME: US
  #         SERIES_TYPE: area
  #     - name: Upload US area enroute artifact
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: enroute
  #         path: US_area_enroute.zip
  # alaska_low:
  #   runs-on: ubuntu-latest
  #   needs: check_edition
  #   if: ${{ needs.check_edition.result == 'success' }}
  #   steps:
  #     - uses: actions/checkout@v3
  #       with:
  #         ref: scripts
  #     - name: Download Alaska low enroute and generate tiles
  #       run: ./enroute_download
  #       env:
  #         GEONAME: Alaska
  #         SERIES_TYPE: low
  #     - name: Upload Alaska low enroute artifact
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: enroute
  #         path: Alaska_low_enroute.zip
  alaska_high:
    runs-on: ubuntu-latest
    needs: check_edition
    if: ${{ needs.check_edition.result == 'success' }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: scripts
      - name: Download Alaska high enroute and generate tiles
        run: ./enroute_download
        env:
          GEONAME: Alaska
          SERIES_TYPE: high
      - name: Upload Alaska high enroute artifact
        uses: actions/upload-artifact@v3
        with:
          name: enroute
          path: Alaska_high_enroute.zip
  pacific_high:
    runs-on: ubuntu-latest
    needs: check_edition
    if: ${{ needs.check_edition.result == 'success' }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: scripts
      - name: Download Pacific high enroute and generate tiles
        run: ./enroute_download
        env:
          GEONAME: Pacific
          SERIES_TYPE: high
      - name: Upload Pacific high enroute artifact
        uses: actions/upload-artifact@v3
        with:
          name: enroute
          path: Pacific_high_enroute.zip
  # caribbean_low:
  #   runs-on: ubuntu-latest
  #   needs: check_edition
  #   if: ${{ needs.check_edition.result == 'success' }}
  #   steps:
  #     - uses: actions/checkout@v3
  #       with:
  #         ref: scripts
  #     - name: Download Caribbean low enroute and generate tiles
  #       run: ./enroute_download
  #       env:
  #         GEONAME: Caribbean
  #         SERIES_TYPE: low
  #     - name: Upload Caribbean low enroute artifact
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: enroute
  #         path: Caribbean_low_enroute.zip
  # caribbean_high:
  #   runs-on: ubuntu-latest
  #   needs: check_edition
  #   if: ${{ needs.check_edition.result == 'success' }}
  #   steps:
  #     - uses: actions/checkout@v3
  #       with:
  #         ref: scripts
  #     - name: Download Caribbean high enroute and generate tiles
  #       run: ./enroute_download
  #       env:
  #         GEONAME: Caribbean
  #         SERIES_TYPE: high
  #     - name: Upload Caribbean high enroute artifact
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: enroute
  #         path: Caribbean_high_enroute.zip
  # caribbean_area:
  #   runs-on: ubuntu-latest
  #   needs: check_edition
  #   if: ${{ needs.check_edition.result == 'success' }}
  #   steps:
  #     - uses: actions/checkout@v3
  #       with:
  #         ref: scripts
  #     - name: Download Caribbean area enroute and generate tiles
  #       run: ./enroute_download
  #       env:
  #         GEONAME: Caribbean
  #         SERIES_TYPE: area
  #     - name: Upload Caribbean area enroute artifact
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: enroute
  #         path: Caribbean_area_enroute.zip
  unpack_and_push:
    runs-on: ubuntu-latest
    needs: [alaska_high, pacific_high]
    steps:
      - uses: actions/checkout@v3
        with:
          sparse-checkout: .
      - uses: actions/download-artifact@v3
        with:
          name: enroute
      - name: Unpack and push enroute tiles
        run: |
          git rm --sparse enroute/*
          unzip *.zip
          rm *.zip
          git add --sparse enroute
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git commit -m "Update enroute tiles $(date +'%Y-%m-%d')"
          git push
